[project]
site_name = "Projet player data &ndash; IFT3150"
site_description = "Site de suivi du projet player data (Tennis Canada) pour le cours IFT3150"
site_author = "Nassim Barhoumi"
site_url = "https://nass1379.github.io/ift3150-player-data/"

copyright = """
&copy; 2026 Nassim Barhoumi &ndash; Projet IFT3150 <br>
Département d'informatique et de recherche opérationnelle <br>
Université de Montréal
"""

repo_name = "nass1379/ift3150-player-data"
repo_url = "https://github.com/nass1379/ift3150-player-data"

# edit_uri = "edit/main/docs/"

nav = [
  { "Vue d'ensemble" = "index.md" },
  { "Suivi" = "suivi.md" },
  { "Synthèse" = "synthese.md" },
  { "Références" = "references.md" },
]


# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

[project.theme]

language = "fr"

features = [
  "navigation.instant",
  "navigation.tabs",
  "navigation.sections",
  "navigation.expand",
  "navigation.top",
  "search.highlight",
  "content.tabs.link",
  "content.code.copy",
  "content.code.annotate",
]
